@startuml
hide footbox

Client -> AnnotationConfigApplicationContext: new

AnnotationConfigApplicationContext -> AnnotationConfigApplicationContext: this()

AnnotationConfigApplicationContext -> AnnotationConfigApplicationContext: register(componentClasses)

AnnotationConfigApplicationContext -> AnnotationConfigApplicationContext: refresh()
@enduml